// Signal Database Types v0.3
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type AssetType = "jp_stock" | "us_stock" | "crypto";
export type SignalAction = "strong_entry_candidate" | "entry_candidate" | "watch" | "wait_for_pullback" | "avoid" | "take_profit_candidate" | "stop_exit_candidate";
export type SignalTier = "S" | "A" | "B" | "C" | "D";
export type TradeSide = "buy" | "sell";
export type PositionStatus = "open" | "closed" | "cancelled";
export type NotificationPriority = "critical" | "high" | "medium" | "low";

export interface Symbol { id: string; symbol: string; name: string | null; asset_type: AssetType; exchange: string | null; currency: string | null; sector: string | null; industry: string | null; country: string | null; is_active: boolean; created_at: string; updated_at: string; }
export interface UniverseMember { id: string; symbol_id: string; universe_type: string; source: string | null; is_enabled: boolean; created_at: string; }
export interface ForbiddenSymbol { id: string; symbol: string; asset_type: AssetType | null; exchange: string | null; reason: string; is_enabled: boolean; created_at: string; }
export interface MarketSnapshot {
  id: string; symbol_id: string; timeframe: string; captured_at: string;
  open: number | null; high: number | null; low: number | null; close: number | null; adjusted_close: number | null; volume: number | null;
  sma20: number | null; sma50: number | null; sma200: number | null; rsi14: number | null; atr14: number | null; atr20: number | null;
  volume_20d_avg: number | null; volume_ratio_20d: number | null; return_1d: number | null; return_5d: number | null; return_20d: number | null; return_60d: number | null;
  high_52w: number | null; low_52w: number | null; distance_from_52w_high_pct: number | null; drawdown_from_recent_high_pct: number | null; turnover: number | null; fundamentals_json: Json | null; catalyst_json: Json | null; raw_json: Json | null;
  data_confidence: number; data_confidence_reason: Json | null; created_at: string;
}
export interface LayerCondition { id: string; layer_name: string; inputs_json: Json | null; scope_key: string; timeframe: string; captured_at: string; condition: string; trend: string; strength: number; risk: number; confidence: number; impact: string; reason: string | null; data_confidence: number; created_at: string; }
export interface Signal { id: string; symbol_id: string; signal_type: string; action_suggestion: SignalAction; tier: SignalTier; opportunity_score: number; entry_timing_score: number; risk_score: number; conviction_score: number; final_entry_score: number; data_confidence: number; tier_reason: string | null; blocker_reason: string | null; strategy_tags_json: Json; strategy_fit_scores_json: Json; detected_at: string; status: string; created_at: string; updated_at: string; }
export interface TradeScenario { id: string; signal_id: string; entry_price: number; stop_price: number; target_base: number | null; risk_reward_base: number | null; created_at: string; }
export interface LlmRun {
  id: string; task_type: string; run_role: string; status: string; input_snapshot_json: Json; output_json: Json | null;
  input_tokens: number | null; output_tokens: number | null; estimated_cost: number | null; latency_ms: number | null; error_message: string | null;
  provider?: string | null; model?: string | null; prompt_version?: string | null; schema_version?: string | null; temperature?: number | null; max_tokens?: number | null;
  repair_attempt_count?: number | null; critic_enabled?: boolean | null; finish_reason?: string | null; estimated_cost_usd?: number | null; request_id?: string | null;
  input_hash?: string | null; output_hash?: string | null; created_at: string;
}
export interface LlmAnalysis { id: string; signal_id: string; action_suggestion: SignalAction | null; confidence: number | null; bull_case: string | null; bear_case: string | null; key_risks_json: Json | null; invalidation_condition: string | null; score_adjustments_json: Json | null; output_json: Json | null; created_at: string; }
export interface LineAlert { id: string; signal_id: string | null; priority: NotificationPriority; message: string; sent_at: string | null; delivery_status: string; user_action: string | null; created_at: string; }
export interface ManualPosition { id: string; symbol_id: string; status: PositionStatus; average_entry_price: number | null; quantity: number | null; stop_price: number | null; opened_at: string | null; closed_at: string | null; created_at: string; updated_at: string; }
export interface PaperTrade { id: string; signal_id: string; symbol_id: string; hypothetical_entry_price: number; stop_price: number | null; target_base: number | null; action_suggestion: SignalAction; created_at: string; }
export interface Outcome { id: string; signal_id: string | null; position_id: string | null; horizon: string; price_at_signal: number | null; price_at_review: number | null; return_pct: number | null; excess_return_pct: number | null; result_label: string | null; reviewed_at: string; created_at: string; }
export interface AnalysisRun { id: string; run_type: string; run_key: string | null; status: string; started_at: string | null; finished_at: string | null; config_json: Json | null; metadata_json: Json | null; engine_version?: string | null; scoring_config_version?: string | null; feature_schema_version?: string | null; prompt_version?: string | null; llm_schema_version?: string | null; universe_type?: string | null; data_source_summary_json?: Json | null; created_at: string; }
export interface ScoreSnapshot { id: string; analysis_run_id: string | null; signal_id: string | null; symbol_id: string | null; symbol: string; captured_at: string; action_suggestion: string; tier: string; opportunity_score: number; entry_timing_score: number; risk_score: number; conviction_score: number; final_entry_score: number; data_confidence: number; score_breakdown_json: Json; score_contributions_json: Json; gate_details_json: Json; decision_reasons_json: Json; strategy_tags_json: Json; strategy_fit_scores_json: Json; input_snapshot_json: Json | null; score_engine_version?: string | null; scoring_config_version?: string | null; feature_snapshot_id?: string | null; market_data_as_of?: string | null; scenario_quality_json?: Json | null; feature_availability_json?: Json | null; score_calibration_version?: string | null; created_at: string; }
export interface StorylineSetRow { id: string; analysis_run_id: string | null; symbol_id: string | null; symbol: string; generated_at: string; status: string; active_scenario: string; revision_summary: string | null; revision_reasons_json: Json; score_snapshot_json: Json; storyline_engine_version?: string | null; scenario_probability_method?: string | null; input_score_snapshot_id?: string | null; llm_run_id?: string | null; data_quality_json?: Json | null; created_at: string; }
export interface StorylineScenarioRow { id: string; storyline_set_id: string; scenario_kind: string; label: string; probability_pct: number; raw_weight?: number | null; normalized_probability_pct?: number | null; horizon: string; thesis: string; expected_return_pct: number; target_price: number; stop_price: number; key_drivers_json: Json; confirmation_signals_json: Json; invalidation_signals_json: Json; risk_notes_json: Json; created_at: string; }
export interface SystemHealthLog { id: string; job_type: string; status: string; error_message: string | null; metrics_json: Json | null; started_at: string | null; finished_at: string | null; created_at: string; }
export interface PriceObservation { id: string; symbol_id: string | null; symbol: string; observed_at: string; timeframe: string; open: number | null; high: number | null; low: number | null; close: number | null; adjusted_close: number | null; volume: number | null; source: string; source_as_of: string | null; raw_json: Json | null; created_at: string; }
export interface SignalOutcome { id: string; score_snapshot_id: string | null; analysis_run_id: string | null; symbol_id: string | null; horizon: string; entry_reference_price: number | null; price_at_horizon: number | null; max_favorable_excursion_pct: number | null; max_adverse_excursion_pct: number | null; return_pct: number | null; benchmark_return_pct: number | null; excess_return_pct: number | null; hit_target_base: boolean | null; hit_stop: boolean | null; rr_realized: number | null; outcome_label: string | null; evaluated_at: string | null; created_at: string; }
export interface StorylineOutcome { id: string; storyline_set_id: string | null; storyline_scenario_id: string | null; symbol_id: string | null; scenario_kind: string; horizon: string; target_price: number | null; stop_price: number | null; actual_close: number | null; actual_high: number | null; actual_low: number | null; scenario_hit: boolean | null; distance_to_target_pct: number | null; distance_to_stop_pct: number | null; review_comment: string | null; evaluated_at: string | null; created_at: string; }
export interface StorylineRevision { id: string; previous_storyline_set_id: string | null; new_storyline_set_id: string | null; symbol_id: string | null; revision_type: string | null; from_active_scenario: string | null; to_active_scenario: string | null; score_delta_json: Json | null; reason_codes_json: Json | null; created_at: string; }
export interface UserDecision { id: string; score_snapshot_id: string | null; storyline_set_id: string | null; symbol_id: string | null; decision: string; decision_reason: string | null; planned_entry_price: number | null; planned_stop_price: number | null; position_size_note: string | null; created_at: string; }
export interface ReviewEvent { id: string; symbol_id: string | null; score_snapshot_id: string | null; storyline_set_id: string | null; event_type: string; severity: string; title: string; details_json: Json | null; resolved_at: string | null; created_at: string; }
export interface DataQualityObservation { id: string; analysis_run_id: string | null; symbol_id: string | null; source: string | null; dataset: string | null; as_of: string | null; freshness_hours: number | null; missing_fields_json: Json | null; confidence_score: number | null; reason_json: Json | null; created_at: string; }
